# Generated by Django 2.2.2 on 2019-07-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='testsuites',
            old_name='testcase_id',
            new_name='testcase',
        ),
    ]
