# Generated by Django 2.2.2 on 2019-07-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20190709_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='group_id',
            new_name='group',
        ),
    ]
