# Generated by Django 2.2.2 on 2019-07-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20190709_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='is_valid',
        ),
    ]
