# Generated by Django 2.2.2 on 2019-07-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_remove_parameter_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='parameters',
            field=models.ManyToManyField(through='Management.TestCaseParameter', to='Management.Parameter'),
        ),
    ]
