# Generated by Django 2.2.2 on 2019-07-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_testcase_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuites',
            name='testcase',
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.TestSuites'),
        ),
    ]
