# Generated by Django 2.2.2 on 2019-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20190709_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuites',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='validate',
            name='name',
        ),
        migrations.AddField(
            model_name='testcase',
            name='seq',
            field=models.IntegerField(default=1, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='testsuites',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='名称'),
        ),
    ]
