# Generated by Django 2.2.2 on 2019-07-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20190709_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuites',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Management.Group'),
        ),
    ]
